### ISSUE TITLE
Error: I don't save key with async-storage from react-native-async-storage

### ISSUE THREAD

**Issue by FromSunNews** [FromSunNews/DongNaiTravelApp#11]
I want to save my username or password when the user press remembers btn then press sign in btn but it does not work when I reload the app. Before I implemented https://github.com/react-native-async-storage/async-storage but failed. It won't save key in local storage. Then I tried this https://docs.expo.dev/versions/latest/sdk/securestore/ but failed again. 

![image](https://user-images.githubusercontent.com/111409554/216075545-2fa9165f-5a1f-459c-97bf-aa55faf24322.png)
I get it here. When I implement successfully, I will close this issue =))

**Comment by NguyenAnhTuan1912** [comment]
Đầu tiên thì mỗi một cái điện thoại là của một người dùng, có nghĩa là chỉ có thể remember một người dùng thôi. Trước tiên vậy đã nhá.
Và nếu như m muốn lưu tất cả thông tin của người dùng đã từng đăng nhập vào đây, thì làm một cái account store giống fb, mối khi ấn remember thì thêm username (email) với password vào. Và trong login thêm một dòng text mới để mở cái store đó lên như là "Login with other accounts" chẳng hạn.

**Comment by FromSunNews** [comment]
After 2 days on internet, finally I resolved this proplem. I using redux-persist, this lib choose [async-storage](https://github.com/react-native-async-storage/async-storage) is where to save data. So I use [async-storage](https://github.com/react-native-async-storage/async-storage) again when storage of this lib nested [async-storage](https://github.com/react-native-async-storage/async-storage). Happy coding =))
