### ISSUE TITLE
New components (by Tuan)

### ISSUE THREAD

**Issue by NguyenAnhTuan1912** [FromSunNews/DongNaiTravelApp#27]
# Update Components
Issue này dùng để giải thích về các components mới được t thêm vào. Bao gồm:
* AppText
* CapsuleButton
* CircleButton

Tụi m có thể vào đây (issue này) để tham khảo hoặc là xem khi code luôn.

# `AppText`
Đây là một component được tuỳ chỉnh lại từ Text Component của React Native. Dùng để chỉnh font, màu chữ. Ngoài ra có hỗ trợ thêm cả truyền đường dẫn vào bên trong text.

```jsx
import { View } from 'react-native'

import { AppText } from 'components'

export default function App() {
  return (
    <View>
      {/* Trả về một text có sự kiện press trong đó. Khi nhấn vào text này thì sẽ tự động chuyển sang Fb */}
      <AppText hyperLink='https://www.facebook.com'>Facebook</AppText>

      {/* Trả về text đã được tuỳ chỉnh theo font và color */}
      <AppText font='h0' color='ext_second'>New text</AppText>

      {/* Trả về text mặc định */}
      <AppText>Đây là một dòng chữ mặc định</AppText>
    </View>
  );
}
```

### `children: string`
Từ hoặc câu cần in ra màn hình. Prop này chỉ được phép nhận vào là kí tự, không nhận vào `object`, `function`, `JSX.Element`.
```jsx
<AppText>Default Text</AppText>
```

#

### `numberOfLines: number`
Thông số này giúp mình custom dòng hiển thị ở trong Text (wrap text), và đi cùng là wrap-text mặc định là Ellipse Mode. Mặc định là `0`, nếu như bằng `0` thì prop này tự động sẽ không được set. Khi mà set bằng 1 thì cho dù text có dài tới đâu thì nó cũng sẽ chỉ cho phép hiện bấy nhiêu dòng đó. Còn lại sẽ được wrap và thu gọn lại và thay vào bằng dấu `...`.
```js
<AppText numberOfLines={0}>Đây là một câu chữ ngắn nhưng có số lượng chữ là cực kì nhiều, để test thử thuộc tính numberOfLines của Text</AppText>
```

#

### `font: string`
Từ khoá liên quan tới font, được quy định trong typography.js. Các từ khoá này là tên của các properties của `app_typo`. Prop này bao gồm một số từ khoá của font đã được quy định từ trước. AppText Sẽ lấy ra typo style tương ứng theo từ khoá style này, bao gồm fontFamily, fontSize.

Các từ khoá ấy bao gồm: `'h0' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'body0' | 'body1' | 'body2' | 'body3' | 'body4' | 'body5' | 'body6' | 'body7' | 'body8' | 'sub0' | 'sub1' | 'sub2' | 'sub3' | 'sub4' | 'sub5'`
```jsx
<View>
  <AppText font='h0'>Đây là title lớn nhất</AppText>
  <AppText font='body2'>Đây là chữ thường lớn thứ 3</AppText>
  <AppText font='sub2'>Đây là chữ phụ lơn thứ 3</AppText>
</View>
```

#

### `color: string`
Từ khoá liên quan tới color, được quy định trong colors.js. Các từ khoá này là tên của các properties của `app_c`. Prop này bao gồm một số từ khoá của color đã được quy định từ trước. AppText sẽ lấy ra color dựa theo từ khoá tương ứng, color này là một object gồm có 2 props là HEX và RGB.

Các từ khoá ấy bao gồm: `'primary' | 'second' | 'third' | 'fourth' | 'sub_primary' | 'sub_second' | 'sub_third' | 'sub_fourth' | 'ext_primary' | 'ext_second' | 'ext_third'`
```jsx
<View>
  <AppText color='primary'>Không thấy được chữ, vì nó trùng màu với màu nền.</AppText>
  <AppText color='fourth'>Chữ này thì thấy được.</AppText>
</View>
```

#

### `hyperLink: string`
Khi link này được truyền vào thì `AppText sẽ giốn như thẻ `a` ở web`. AppText sẽ trả về một Text component có sự kiện Press. Khi ấn vào thì nó sẽ chuyển sang web, app khác.
```js
<View>
  <AppText hyperLink='https://www.facebook.com'>Facebook</AppText>
  <AppText hyperLink='https://www.youtube.com'>Youtube</AppText>
  <AppText hyperLink='https://www.instagram.com'>Instagram</AppText>
</View>
```

#

### `style: StyleProp<ViewStyle>`
Cutome style cho Text.
```js
<AppText style={{ color: 'red', fontWeight = 900 }}>Đây là chữ đậm, màu đỏ</AppText>
```

**Comment by NguyenAnhTuan1912** [comment]
# `CapsuleButton`
Capsule Button là những button nhỏ ở trong app, hình dạng của nút này giống với một viên thuốc nén. Có thể chứa cả text lẫn icon hoặc chỉ có mỗi text, nếu chỉ chứa mỗi icon thì xem thêm `CircleButton` bên dưới.

```jsx
import { View } from 'react-native'

import { CapsuleButton } from 'components'

export default function App() {
  const handlePressTag = () => {}

  return (
    <View>
      {/* Trả về một capsule button mặc định */}
      <CapsuleButton>Facebook</CapsuleButton>

      {/* Trả về một capsule button với hàm xử lý press và các config mặc định của nút. */}
      <CapsuleButton handlePressButton={handlePressTag}>Instagram</CapsuleButton>

      {/* Trả về một capsule button với màu mới (khác mặc định) khi được active hay focus. */}
      <CapsuleButton activeColor="type_2">Yotube</CapsuleButton>
    </View>
  )
}
```

## Props
### `children: string`
Từ hoặc câu cần in ra màn hình. Prop này chỉ được phép nhận vào là kí tự, không nhận vào `object`, `function`, `JSX.Element`.
```jsx
<CapsuleButton>Facebook</CapsuleButton>
```

#

### `isActive: boolean`
__Default value: `false`__

Check xem là button này có được active hay chưa. Dùng với một số chức năng như check xem hiện tại bài đăng này có đang đuọc người dùng yêu thích hay không? Hiện tại đang xem danh mục nào?. Value mặc định của prop này là  `false` và nếu như prop này `false` thì nó sẽ hiển thị màu mặc định.
```js
<CapsuleButton isActive={false}>Facebook</CapsuleButton>
```

#

### `isDisable: boolean`
__Default value: `false`__

Prop này dùng để tắt các button. Button khi tắt đi thì sẽ không thể ấn và màu sẽ nhạt hơn. Value của props này mặc định là 
```jsx
<CapsuleButton isDisable={false}>Facebook</CapsuleButton>
```

#

### `defaultColor: string`
__Default value: `type_1`__

Prop này sẽ quy định màu sắc cho button. Màu này là một bộ màu đuọc mix lại dành riêng cho buttons. Cái này thì để mai t thêm một issue về màu trong này hoặc tạm thời có thể xem trên figma, ở trang Roles & Stylesheet.

Prop này có các type như: `'type_1' | 'type_2' | 'type_3'`
```jsx
<CapsuleButton defaultColor="type_1">Button này có màu mặc  định là type 1</CapsuleButton>
```

#

### `activeColor: string`
Prop này sẽ quy định màu sắc cho button khi button này được active hoặc đang được focus. Màu này là một bộ màu đuọc mix lại dành riêng cho buttons.

Prop này có các type như: `'type_1' | 'type_2'`
```js
<CapsuleButton isActive={true} activeColor="type_1" >Active</CapsuleButton>
```

#

### `boxShadowType: string`
Prop này sẽ quy định shadow cho button khi button. Hiện tại trong project có 5 loại shadow.

Prop này có các style mặc định như: `'type_1' | 'type_2' | 'type_3' | 'type_4' | 'type_5'`
```js
<CapsuleButton boxShadowType="type_2" >Shadow is dropped!</CapsuleButton>
```

#

### `setIcon: Function<JSX.Element>`
Prop này là một function dùng để load Icon. Function này nhận vào 2 tham số là `isActive: boolean` và `currentLabelStyle: StyleSheet`.

___*Lưu ý*___: khi thêm icon thì Icon đó nên được trả về từ một function (vì tiện, và function này đuọc nhận một số param cần thiết để tự động chỉnh lại Icon khi button thay đổi).
```js
{/* Good */}
<CapsuleButton
        setIcon={(isActive, currentLabelStyle) => {
          <Ionicons name={isActive ? 'map' : 'map-outline'} style={currentLabelStyle} /
        }}
      >
        Map
      </CapsuleButton>
```
```js
{/* Bad*/}
<CapsuleButton
        setIcon={<Ionicons name='map' style={{color: 'red'}} />}
      >
        Map
      </CapsuleButton>
```

**Comment by NguyenAnhTuan1912** [comment]
# `CircleButton`
Circle Button là những button nhỏ ở trong app, có hình dạng là một hình tròn. Button này chỉ có icon chứ không có text.

```jsx
import { View } from 'react-native'

import Ionicons from 'react-native-vector-icons/Ionicons'

import { CircleButton } from 'components'

export default function App() {
  const handlePressTag = () => {}

  return (
    <View>
      {/* Trả về một capsule button mặc định, button mặc định thường không có gì ngoài background color của button */}
      <CircleButton />

      {/* Trả về một capsule button mặc định, button này có icon */}
      <CircleButton setIcon={() => <Ionicons name="home" />} />

      {/* Trả về một capsule button với hàm xử lý press và các config mặc định của nút. */}
      <CapsuleButton handlePressButton={handlePressTag} />

      {/* Trả về một capsule button với màu mới (khác mặc định) khi được active hay focus. */}
      <CapsuleButton activeColor="type_2" />
    </View>
  )
}
```

## Props
### `isActive: boolean`
__Default value: `false`__

Check xem là button này có được active hay chưa. Dùng với một số chức năng như check xem hiện tại bài đăng này có đang đuọc người dùng yêu thích hay không? Hiện tại đang xem danh mục nào?. Value mặc định của prop này là  `false` và nếu như prop này `false` thì nó sẽ hiển thị màu mặc định.
```js
<CircleButton  isActive={false} />
```

#

### `isDisable: boolean`
__Default value: `false`__

Prop này dùng để tắt các button. Button khi tắt đi thì sẽ không thể ấn và màu sẽ nhạt hơn. Value của props này mặc định là 
```jsx
<CircleButton  isDisable={false} />
```

#

### `defaultColor: string`
__Default value: `type_1`__

Prop này sẽ quy định màu sắc cho button. Màu này là một bộ màu đuọc mix lại dành riêng cho buttons. Cái này thì để mai t thêm một issue về màu trong này hoặc tạm thời có thể xem trên figma, ở trang Roles & Stylesheet.

Prop này có các type như: `'type_1' | 'type_2' | 'type_3'`
```jsx
<CircleButton defaultColor="type_1" />
```

#

### `activeColor: string`
__Default value: `type_1`__

Prop này sẽ quy định màu sắc cho button khi button này được active hoặc đang được focus. Màu này là một bộ màu đuọc mix lại dành riêng cho buttons.

Prop này có các type như: `'type_1' | 'type_2'`
```jsx
<CircleButton isActive={true} activeColor="type_1" />
```

#

### `boxShadowType: string`
__Default value: ""__

Prop này sẽ quy định shadow cho button khi button. Hiện tại trong project có 5 loại shadow.

Prop này có các style mặc định như: `'type_1' | 'type_2' | 'type_3' | 'type_4' | 'type_5'`
```jsx
<CircleButton boxShadowType="type_2"  />
```

#

### `setIcon: Function<JSX.Element>`
Prop này là một function dùng để load Icon. Function này nhận vào 2 tham số là `isActive: boolean` và `currentLabelStyle: StyleSheet`.

___*Lưu ý*___: khi thêm icon thì Icon đó nên được trả về từ một function (vì tiện, và function này đuọc nhận một số param cần thiết để tự động chỉnh lại Icon khi button thay đổi).
```jsx
{/* Good */}
<CircleButton
  setIcon={(isActive, currentLabelStyle) => {
    <Ionicons name={isActive ? 'map' : 'map-outline'} style={currentLabelStyle} />
  }}
/>
```
```jsx
{/* Bad*/}
<CircleButton
  setIcon={<Ionicons name='map' style={{color: 'red'}} />}
/>
```

#

### `handlePressButton: Function<void>`
Đây là một hàm xử lý sự kiện `onPress` của button.

```jsx
import { View } from 'react-native'

import { CircleButton } from 'components'

export default function App() {
  const handlePressTag = () => {}

  return (
    <View>
      <CircleButton
        handlePressButton={handlePressTag}
      />
    </View>
  )
}
```

**Comment by FromSunNews** [comment]
Ok. Sir
